/* ─────────────────────────────────────────────────────────────────────────────
   EUDR Schema — Firebird 2.5
   Run once against the target database (isql or FlameRobin).
   ───────────────────────────────────────────────────────────────────────────── */

/* ── Generators ─────────────────────────────────────────────────────────────── */
CREATE GENERATOR GEN_EUDR_RUN_ID;
CREATE GENERATOR GEN_EUDR_RUN_ITEM_ID;
CREATE GENERATOR GEN_EUDR_INBOX_ID;
CREATE GENERATOR GEN_EUDR_JOURNAL_ID;
CREATE GENERATOR GEN_EUDR_SUMMARY_ID;

COMMIT;

/* ── EUDR_RUN — one row per nightly batch attempt ──────────────────────────── */
CREATE TABLE EUDR_RUN (
    RUN_ID        INDEKSS      NOT NULL,
    BUSINESS_DATE DDATE    NOT NULL,
    STATUS        V_KOD  NOT NULL,   /* RUNNING | DONE | FAILED */
    STARTED_AT    DDATE    NOT NULL,
    FINISHED_AT   DDATE,
    CONSTRAINT PK_EUDR_RUN PRIMARY KEY (RUN_ID),
    CONSTRAINT CK_EUDR_RUN_STATUS CHECK (STATUS IN ('RUNNING','DONE','FAILED'))
);

SET TERM ^ ;
CREATE TRIGGER TRG_EUDR_RUN_BI FOR EUDR_RUN
ACTIVE BEFORE INSERT POSITION 0
AS BEGIN
    IF (NEW.RUN_ID IS NULL) THEN
        NEW.RUN_ID = GEN_ID(GEN_EUDR_RUN_ID, 1);
END^
SET TERM ; ^

COMMIT;

/* ── EUDR_INBOX — events fed by the Ingester from RabbitMQ ─────────────────── */
CREATE TABLE EUDR_INBOX (
    EVENT_ID        INDEKSS      NOT NULL,
    MAG_DOK_NAG_ID  INDEKSS     NOT NULL,
    EUDR_TYPE       INDEKSS     NOT NULL,   /* EudrEventType enum ordinal */
    DIRECTION       V_KOD  NOT NULL,   /* FORWARD | REVERSE */
    SERIA_ID        INDEKSS     NOT NULL,
    OCCURRENCE_SEQ  INDEKSS      NOT NULL,
    EVENT_TIMESTAMP DDATE   NOT NULL,
    BUSINESS_DATE   DDATE   NOT NULL,
    CONSTRAINT PK_EUDR_INBOX PRIMARY KEY (EVENT_ID)
);

CREATE INDEX IDX_EUDR_INBOX_DATE ON EUDR_INBOX (BUSINESS_DATE);
CREATE INDEX IDX_EUDR_INBOX_SEQ  ON EUDR_INBOX (OCCURRENCE_SEQ);

SET TERM ^ ;
CREATE TRIGGER TRG_EUDR_INBOX_BI FOR EUDR_INBOX
ACTIVE BEFORE INSERT POSITION 0
AS BEGIN
    IF (NEW.EVENT_ID IS NULL) THEN
        NEW.EVENT_ID = GEN_ID(GEN_EUDR_INBOX_ID, 1);
END^
SET TERM ; ^

COMMIT;

/* ── EUDR_EVENT_JOURNAL — reconciliation cross-check ───────────────────────── */
CREATE TABLE EUDR_EVENT_JOURNAL (
    ID             INDEKSS      NOT NULL,
    EVENT_ID       INDEKSS      NOT NULL,
    BUSINESS_DATE  DDATE   NOT NULL,
    OCCURRENCE_SEQ INDEKSS      NOT NULL,
    CONSTRAINT PK_EUDR_JOURNAL PRIMARY KEY (ID)
);

CREATE INDEX IDX_EUDR_JOURNAL_DATE ON EUDR_EVENT_JOURNAL (BUSINESS_DATE);
CREATE INDEX IDX_EUDR_JOURNAL_EVT  ON EUDR_EVENT_JOURNAL (EVENT_ID);

SET TERM ^ ;
CREATE TRIGGER TRG_EUDR_JOURNAL_BI FOR EUDR_EVENT_JOURNAL
ACTIVE BEFORE INSERT POSITION 0
AS BEGIN
    IF (NEW.ID IS NULL) THEN
        NEW.ID = GEN_ID(GEN_EUDR_JOURNAL_ID, 1);
END^
SET TERM ; ^

COMMIT;

/* ── EUDR_RUN_ITEM — one row per event processed in a run ──────────────────── */
CREATE TABLE EUDR_RUN_ITEM (
    ITEM_ID        INDEKSS      NOT NULL,
    RUN_ID         INDEKSS      NOT NULL,
    EVENT_ID       INDEKSS       NOT NULL,
    MAG_DOK_NAG_ID INDEKSS      NOT NULL,
    EVENT_TYPE     INDEKSS      NOT NULL,
    DIRECTION      V_KOD   NOT NULL,   /* FORWARD | REVERSE */
    OUTCOME        V_KOD  NOT NULL,   /* OK | SKIPPED | SHORTAGE | FAILED */
    NOTES          V_1000,
    CONSTRAINT PK_EUDR_RUN_ITEM PRIMARY KEY (ITEM_ID),
    CONSTRAINT FK_EUDR_RUN_ITEM_RUN FOREIGN KEY (RUN_ID) REFERENCES EUDR_RUN (RUN_ID)
);

CREATE INDEX IDX_EUDR_RUN_ITEM_RUN ON EUDR_RUN_ITEM (RUN_ID);
CREATE INDEX IDX_EUDR_RUN_ITEM_EVT ON EUDR_RUN_ITEM (EVENT_ID);

SET TERM ^ ;
CREATE TRIGGER TRG_EUDR_RUN_ITEM_BI FOR EUDR_RUN_ITEM
ACTIVE BEFORE INSERT POSITION 0
AS BEGIN
    IF (NEW.ITEM_ID IS NULL) THEN
        NEW.ITEM_ID = GEN_ID(GEN_EUDR_RUN_ITEM_ID, 1);
END^
SET TERM ; ^

COMMIT;

/* ── EUDR_RAW_MATERIALS_SUMMARY — append-only EUDR ledger ──────────────────── */
CREATE TABLE EUDR_RAW_MATERIALS_SUMMARY (
    ID                              INDEKSS         NOT NULL,
    TRANSACTION_TYPE                V_KOD     NOT NULL,   /* RIN RPR RZU OUT ZWR PKS */
    DIRECTION                       V_KOD     NOT NULL,   /* FORWARD | REVERSE */
    MAG_DOK_NAG_ID                  INDEKSS        NOT NULL,
    MAG_DOK_SPEC_ID                 INDEKSS,
    SERIA_ID                        INDEKSS        NOT NULL,
    BUSINESS_DATE                   DDATE      NOT NULL,
    ZAMIENNIK_KOD                   V50_UNICODE,
    ART_ID                          INDEKSS        NOT NULL,
    RAW_MATERIAL_ILOSC              NUMERY_P3  NOT NULL,
    RAW_MATERIAL_ETYKIETA_ILOSC_ROZ NUMERY_P3,
    ETYKIETA                        V50_UNICODE,
    DDS                             V50_UNICODE,
    LOT                             V50_UNICODE,
    SUPPLIER_KOD                    V50_UNICODE,
    SUPPLIER_NAZWA                  V100,
    ZAM_NUMER                       V50_UNICODE,
    NS                              INDEKSS,
    FINISHED_PRODUCT_SESSION_ID     V50_UNICODE,
    RAW_MATERIAL_SESSION_ID         INDEKSS,
    TRACE_LEVEL                     INDEKSS        NOT NULL,
    REFERENCE_NUMBER                V50_UNICODE,
    CONSTRAINT PK_EUDR_SUMMARY PRIMARY KEY (ID),
    CONSTRAINT CK_EUDR_SUMMARY_TXTYPE CHECK (
        TRANSACTION_TYPE IN ('RIN','RPR','RZU','OUT','ZWR','PKS')
    ),
    CONSTRAINT CK_EUDR_SUMMARY_DIR CHECK (DIRECTION IN ('FORWARD','REVERSE'))
);

/* Idempotency check (MAG_DOK_NAG_ID + type + direction) */
CREATE INDEX IDX_EUDR_SUMMARY_NAG  ON EUDR_RAW_MATERIALS_SUMMARY (MAG_DOK_NAG_ID, TRANSACTION_TYPE, DIRECTION);
/* RPR/ZWR source lookup by spec */
CREATE INDEX IDX_EUDR_SUMMARY_SPEC ON EUDR_RAW_MATERIALS_SUMMARY (MAG_DOK_SPEC_ID, TRANSACTION_TYPE);
/* FIFO source scan (zamiennik_kod + seria_id + type + direction) */
CREATE INDEX IDX_EUDR_SUMMARY_KOD  ON EUDR_RAW_MATERIALS_SUMMARY (ZAMIENNIK_KOD, SERIA_ID, TRANSACTION_TYPE, DIRECTION);
/* OUT handler — RZU rows by NS */
CREATE INDEX IDX_EUDR_SUMMARY_NS   ON EUDR_RAW_MATERIALS_SUMMARY (NS, TRANSACTION_TYPE, DIRECTION);

SET TERM ^ ;
CREATE TRIGGER TRG_EUDR_SUMMARY_BI FOR EUDR_RAW_MATERIALS_SUMMARY
ACTIVE BEFORE INSERT POSITION 0
AS BEGIN
    IF (NEW.ID IS NULL) THEN
        NEW.ID = GEN_ID(GEN_EUDR_SUMMARY_ID, 1);
END^
SET TERM ; ^

COMMIT;
